# 포드 정보 입력
server:
  port: 8080

# DataSource 설정 (h2)
spring:
  datasource:
    url: jdbc:h2:mem:oauth
    driverClassName: org.h2.Driver
    username: sa
    passsword:
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
#      ddl-auto: create 
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  
  