# 포드 정보 입력
server:
  port: 8080

# DataSource 설정 (h2)
spring:
  datasource.url: jdbc:h2:mem:oauth
  driverClassName: org.h2.Driver
  username: sa
  passsword:
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: create # 실행할 때마다 Database 생성 
    database-platform: org.hibernate.dialect.H2Dialect