# 포드 정보 입력
server:
  port: 8080

# DataSource 설정 (h2)
spring:
  datasource:
    url: jdbc:h2:mem:oauth
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enable: true